### ISSUE TITLE
Log Data

### ISSUE THREAD

**Issue by PureDJ** [Meesen0743/MHI-RC-to-MQTT#1]
I Setup the remote software on an old XP machine (it does not run under 7 and 10) and setup a serial port sniffer.
(The MHI-RC has internally a USB to Serial converter, communication is actually thru a serial port)
Th topic is MHI RC-to-MQTT, however the remote goes in to lock when you connect the PC and run the remote control software.
Better would be to reverse engineer the X Y signals.
However I have attached the raw sniff files, they should be processed, hopefully this will help.

[AircoData.zip](https://github.com/Meesen0743/MHI-RC-to-MQTT/files/4980274/AircoData.zip)

**Comment by Meesen0743** [comment]
Thanks @PureDJ Going forward I will be looking at the XY signals.
I believe they have implemented the Home Bus System (HSB) to both carry the 17v the Rc-Ex3 controller operates on and also for communications.
